# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # Use "yarn" or "pnpm" if you use those package managers instead
    directory: "/" # Assuming your package.json is in the root directory
    schedule:
      interval: "daily" # You can change this to "weekly" if daily is too noisy
    
    # This rule restricts updates to minor and patch versions only
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
