apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ghmap
  name: next-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: next-client
          image: fswoon2/alexwfs:github-map
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: https://ghmap.fswoon.au/api/v1
      imagePullSecrets:
        - name: regcred
     
